# Generated by Django 5.0.3 on 2024-03-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('back', 'Back'), ('bicep', 'Bicep'), ('chest', 'Chest'), ('delts', 'Delts'), ('glutes', 'Glutes'), ('hamstring', 'Hamstring'), ('quads', 'Quads'), ('triceps', 'Triceps')], max_length=20)),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
