# Generated by Django 5.0.3 on 2024-03-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_workoutrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutrecord',
            name='workout_type',
            field=models.CharField(max_length=20),
        ),
    ]
