# Generated by Django 5.0.3 on 2024-03-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_workoutrecord_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
