# Generated by Django 5.0.3 on 2024-03-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_workoutrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
