# Generated by Django 5.0.1 on 2024-04-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal_completed',
            new_name='completed',
        ),
    ]
